apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: limbo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: limbo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: limbo
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - name: limbo
        image: limbo:local
        imagePullPolicy: Never
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      restartPolicy: Always
      securityContext: {}
